# Training Configuration
# =====================
# Edit these values and push to trigger training with your desired settings.
# These values are used when the workflow is triggered by a push event.
# For manual runs via GitHub Actions UI, you can override these with workflow_dispatch inputs.

model: "microsoft/deberta-v3-base"
epochs: 10
batch_size: 4
learning_rate: "1e-5"
max_seq_length: 27
optimizer: "adamw_torch"
scheduler: "cosine"
gradient_accumulation: 16
mixed_precision: "fp16"
weight_decay: "0.01"
warmup_ratio: "0.1"
push_to_hub: true
hf_repo: "RyIoT33/haystack-autotagging"

# GPU Options: "T4", "L4", "A10", "A100", "A100-40GB", "A100-80GB", "L40S", "H100", "H200", "B200"
gpu: "A10"
